name: patchpal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6

  provider: ^6.1.1
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.1.0 
  tflite_flutter: ^0.10.1
  path_provider: ^2.1.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/patchpal_logo.png
    - .env

